# Generated by Django 3.0.3 on 2020-03-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_event_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
